server:
  port: 3000
spring:
  profiles:
    default: dev
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
  application:
    name: yufu-identity
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/yufu-identity?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000